"""add ondelete SET NULL to user FK references

Revision ID: d824b9a82b0d
Revises: d3f8a1b2c4e5
Create Date: 2026-03-06 01:47:54.059821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd824b9a82b0d'
down_revision: Union[str, None] = 'd3f8a1b2c4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('groups_created_by_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('resource_permissions', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('resource_permissions_owner_id_fkey'), 'resource_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'resource_permissions', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('resource_shares', 'granted_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('resource_shares_granted_by_fkey'), 'resource_shares', type_='foreignkey')
    op.create_foreign_key(None, 'resource_shares', 'users', ['granted_by'], ['id'], ondelete='SET NULL')
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('workspaces_created_by_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_created_by_fkey'), 'workspaces', 'users', ['created_by'], ['id'])
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'resource_shares', type_='foreignkey')
    op.create_foreign_key(op.f('resource_shares_granted_by_fkey'), 'resource_shares', 'users', ['granted_by'], ['id'])
    op.alter_column('resource_shares', 'granted_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'resource_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('resource_permissions_owner_id_fkey'), 'resource_permissions', 'users', ['owner_id'], ['id'])
    op.alter_column('resource_permissions', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_created_by_fkey'), 'groups', 'users', ['created_by'], ['id'])
    op.alter_column('groups', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
